# Example Site settings

#google_analytics: UA-NNNNNNNN-N
title: 'k0mr4d3'
description: "Where I write about everything"
baseurl: "/"
url: "https://k0mr4d3.github.io"

header_pages:
  - index.md
#  - about.md

footer: '<a href="https://twitter.com/k0mr4d352">twitter</a> | <a href="https://instagram.com/k0mr4d3_52">instagram</a>'

style: hacker # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag

remote_theme: b2a3e8/jekyll-theme-console
